version: '3.8'

services:
  clash:
    image: dreamacro/clash
    restart: always
    volumes:
      - ./config.yaml:/root/.config/clash/config.yaml:ro
      # - ./ui:/ui:ro # dashboard volume
    ports:
      - "7890:7890"
      - "7891:7891"
      # - "18080:8080" # The External Controller (RESTful API)

  gpt-proxy:
    image: cphovo/gpt-proxy
    restart: always
    ports:
      - 19090:9090
    environment:
      - http_proxy=clash:7890