version: '3.8'

services:
  # proxy
  clash:
    image: dreamacro/clash
    restart: always
    volumes:
      - ./config.yaml:/root/.config/clash/config.yaml:ro
    ports:
      - "7890:7890"
      - "7891:7891"

  # cloudflare bypass 
  gpt-proxy:
    image: gpt-proxy
    restart: always
    ports:
      - 19090:9090
    environment:
      - http_proxy=http://clash:7890
    depends_on:
      - clash

  # translate service
  deepl:
    image: missuo/deeplx:latest
    restart: always
    ports:
      - 1188:1188
